(()=>{'use strict';
const C=window.COURSE, KEY='regression-workbench-v1',DAY=86400000,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fresh=()=>({version:1,seen:{},attempts:[],notes:{},diagnosis:null,exam:null,history:[]});let S=fresh(),persistent=true;try{S=validate(JSON.parse(localStorage.getItem(KEY)))||fresh()}catch{};
function validate(x){
if(!x||x.version!==1||!Array.isArray(x.attempts)||!Array.isArray(x.history)||!x.seen||typeof x.seen!=='object'||!x.notes||typeof x.notes!=='object')return null;
if(x.attempts.some(a=>!a||!C.questions.some(q=>q.id===a.id)||typeof a.ok!=='boolean'||!Number.isFinite(a.time)))return null;
const s=fresh();s.seen=Object.fromEntries(Object.entries(x.seen).filter(([k,v])=>C.lessons.some(l=>l.id===k)&&Number.isFinite(v)));s.notes=Object.fromEntries(Object.entries(x.notes).filter(([k,v])=>typeof v==='string'&&v.length<=20000&&k!=='__proto__'));
s.attempts=x.attempts.slice(-5000).map(a=>({id:a.id,ok:a.ok,time:a.time,hint:!!a.hint,review:!!a.review,value:String(a.value||'').slice(0,100)}));
if(x.diagnosis&&Number.isFinite(x.diagnosis.time)&&Array.isArray(x.diagnosis.weak))s.diagnosis={time:x.diagnosis.time,weak:x.diagnosis.weak.filter(id=>C.lessons.some(l=>l.id===id))};
s.history=x.history.filter(h=>h&&['A','B'].includes(h.version)&&Number.isFinite(h.time)&&Number.isFinite(h.score)&&h.score>=0&&h.score<=86).slice(0,30).map(h=>({version:h.version,time:h.time,score:h.score,...(Number.isFinite(h.manual)&&h.manual>=0&&h.manual<=14?{manual:h.manual}:{})}));
if(x.exam){let e=x.exam;if(!['A','B'].includes(e.version)||!Number.isFinite(e.start)||!Number.isFinite(e.end)||e.end<=e.start||!e.answers||typeof e.answers!=='object'||typeof e.proof!=='string'||typeof e.submitted!=='boolean')return null;
s.exam={version:e.version,start:e.start,end:e.end,answers:Object.fromEntries(Object.entries(e.answers).filter(([k,v])=>/^e\d+[abcd]?$/.test(k)&&typeof v==='string').map(([k,v])=>[k,v.slice(0,100)])),proof:e.proof.slice(0,20000),submitted:e.submitted};
if(e.submitted){if(!Number.isFinite(e.score)||!Number.isFinite(e.submittedAt))return null;Object.assign(s.exam,{score:Math.max(0,Math.min(86,e.score)),submittedAt:e.submittedAt});if(Array.isArray(e.manualChecks)){s.exam.manualChecks=[0,1,2,3].filter(i=>e.manualChecks.includes(i));s.exam.manual=s.exam.manualChecks.reduce((a,i)=>a+[4,4,4,2][i],0)}}
}return s}

function save(){try{localStorage.setItem(KEY,JSON.stringify(S))}catch{persistent=false;toast('无法保存到浏览器，请导出学习备份。')}}function toast(t){$('#toast').textContent=t;setTimeout(()=>$('#toast').textContent='',4200)}
const lesson=id=>C.lessons.find(l=>l.id===id),qby=id=>C.questions.find(q=>q.id===id),link=(id,t)=>`<a class="btn secondary small-btn" href="#learn/${id}">${esc(t||lesson(id).title)}</a>`;
function status(l){const a=C.questions.filter(q=>q.lesson===l.id).map(q=>S.attempts.filter(a=>a.id===q.id).at(-1)).filter(Boolean),good=a.filter(a=>a.ok&&!a.hint);return good.length>=2&&good.some(a=>qby(a.id).transfer)?(good.some(a=>a.review)?'复习通过':'练习通过'):S.seen[l.id]?'正在学习':'未开始'}
function next(){const weak=S.diagnosis?.weak||[];return C.lessons.find(l=>weak.includes(l.id)&&!status(l).includes('通过'))||C.lessons.find(l=>!status(l).includes('通过'))||C.lessons[0]}
function due(){return C.questions.filter(q=>{let a=S.attempts.filter(a=>a.id===q.id).at(-1);return a&&(!a.ok||a.time+(a.review?3:1)*DAY<=Date.now())})}
const nav=[['today','◷','今天学什么'],['path','▦','全课程 · 14 章'],['labs','⌁','互动实验'],['review','↻','错题复习'],['exam','▤','模拟测验'],['resources','☷','资源与备份']];
function shell(body,route){$('#app').innerHTML=`<div class="shell"><aside class="sidebar"><a class="brand" href="#today"><span class="brand-icon">∑</span>回归练习室</a><div class="brand-small">高维数据分析 · 2026 秋</div><nav>${nav.map(([id,i,t])=>`<a class="nav-link ${route===id?'active':''}" href="#${id}"><span class="nav-symbol">${i}</span>${t}</a>`).join('')}</nav><div class="sidebar-foot">每天 30 分钟<br>先补基础，再跟课程。</div></aside><div class="main-wrap"><header class="topbar"><span>高维数据分析 / 学习工作台</span><span class="small">${persistent?'进度仅存当前浏览器':'保存不可用，请及时导出'}</span></header><main id="main" class="content" tabindex="-1">${body}</main></div></div><nav class="mobile-menu" aria-label="主要导航">${nav.map(([id,i,t])=>`<a class="${route===id?'active':''}" href="#${id}"><span class="nav-symbol">${i}</span>${({today:'今天',path:'路线',labs:'实验',review:'复习',exam:'测验',resources:'资源'})[id]}</a>`).join('')}</nav>`}
const heading=(a,b)=>`<div class="page-heading"><div><div class="eyebrow">回归练习室 / LEARN BY DOING</div><h1>${a}</h1><p class="muted">${b}</p></div></div>`;
function today(){let l=next(),n=C.lessons.filter(l=>status(l).includes('通过')).length;shell(heading('今天，先弄懂一小步','30 分钟 · 先补基础再跟课 · 不用一次读完整章')+`<section class="card soft section-space"><h2>没学过 R？先从这里开始</h2><p>8 节小课：计算器 → 给对象起名字 → 一组数 → 数据表 → 读文件 → 画图 → 回归 → 查错。先学 R 主线，不用同时学 Python。</p><a class="btn" href="#rstart">进入 R 零基础入门 →</a></section><div class="grid grid-main section-space"><section class="lesson-hero"><div class="hero-inner"><span class="tag">${l.group}</span><h2 class="lesson-title">${l.title}</h2><p>${l.simple}</p><ol class="step-list"><li><span class="step-no">5′</span><div><strong>先回忆</strong><p>有到期题就复习；初次学习先做基础诊断。</p></div></li><li><span class="step-no">15′</span><div><strong>理解一个知识点</strong><p>${l.method}</p></div></li><li><span class="step-no">10′</span><div><strong>独立做题，再说理由</strong><p>先答再看提示。错了就回到缺失的那一步。</p></div></li></ol></div><div class="hero-bottom"><a class="btn" href="#learn/${l.id}">开始今天的学习 →</a><a href="#diagnostic">${S.diagnosis?'重做基础诊断':'先做 8 题基础诊断'}</a></div></section><aside class="grid"><section class="card"><h2>你的学习证据</h2><div class="stat-row"><div class="stat"><strong>${n} / ${C.lessons.length}</strong><span>全部学习单元通过</span></div><div class="stat"><strong>${due().length}</strong><span>待纠错 / 到期题</span></div></div><div class="progress-track"><div class="progress-fill" style="width:${n/C.lessons.length*100}%"></div></div><p class="small muted">每节至少 2 道独立答对，且包含迁移题，才算练习通过。读过不等于掌握。</p><a href="#review">打开复习队列 →</a></section><section class="card soft"><h3>卡住不是只能重读</h3><p>看不懂符号：展开成数字。<br>会算但不懂：拖动图形做预测。<br>推导断了：逐步补齐依据。<br>代码看不懂：追踪每行输入输出。</p></section></aside></div><section class="card section-space"><h2>整门课都在这里</h2><p><a class="btn secondary" href="#path">打开 14 章 · 66 小节目录 →</a></p><p>${C.scope}</p><p class="small muted">${C.sourceNote}</p></section>`,'today')}
const chapterLessons=ch=>[...new Set([...ch.sections.flatMap(s=>s.lessons),...(ch.extras||[])])];
function chapterStats(ch){let ids=chapterLessons(ch);return {total:ids.length,passed:ids.filter(id=>status(lesson(id)).includes('通过')).length}}
function path(){shell(heading('全课程 · 14 章','对照教学大纲的 66 个小节。选择章节进入讲解、例题、练习和应用任务。')+`<section class="card"><div class="actions"><a class="btn" href="#rstart">R 零基础入门（8 节）</a><a class="btn secondary" href="#foundations">数学与通用基础（11 个单元）</a><a class="btn secondary" href="#coursecheck">全课程 28 题自测</a></div><p class="small muted section-space">前 3 讲结合已提供讲义；后续主题按大纲与公开教材补全。第十四章暂定。实际考试范围与权重以教师公布为准。</p><label class="field">查找知识点<input id="course-search" type="search" placeholder="例如：Lasso、样条、低秩、预测"></label><div id="search-results"></div></section><div class="grid grid-2 section-space">${C.chapters.map(ch=>{let st=chapterStats(ch);return `<section class="card chapter-card"><div class="actions"><span class="tag">第 ${ch.id} 章</span>${ch.tentative?'<span class="tag amber">大纲暂定</span>':''}</div><h2>${ch.title}</h2><p class="small">${ch.objective}</p><p class="small muted">${ch.sections.length} 小节 · ${st.passed}/${st.total} 关联单元练习通过</p><div class="progress-track"><div class="progress-fill" style="width:${st.passed/st.total*100}%"></div></div><p class="section-space"><a class="btn secondary" href="#chapter/${ch.id}">进入这一章 →</a></p></section>`}).join('')}</div>`,'path');$('#course-search').oninput=e=>{let v=e.target.value.trim().toLowerCase();$('#search-results').innerHTML=v?C.lessons.filter(l=>(l.title+' '+l.formula+' '+l.intro.join(' ')).toLowerCase().includes(v)).map(l=>`<p>${link(l.id)} <span class="small muted">${l.group}</span></p>`).join('')||'<p>未找到。可尝试中文名称或查看章目录。</p>':''}}
function rStart(){shell(heading('R 从零开始','不需要任何编程经验。手机先读懂，电脑再亲手运行；每天选一节，可拆成两天。')+`<section class="card soft"><h2>今天只做一件事：让 R 算 2 + 3</h2><p>先做 5 分钟演示，花 15 分钟理解本节的几个符号，再用 10 分钟做题或在电脑改一行代码。不会时回到上一小步。</p><div class="actions">${link('rstart','开始第 1 节')}<a class="btn secondary" href="#rtrace/rstart">直接看第一段演示</a></div></section><div class="route-list section-space">${C.rpath.map(id=>{let l=lesson(id);return `<a class="route-item" href="#learn/${id}"><div><strong>${l.title}</strong><p class="small muted">约 15—30 分钟 · 讲解、逐行演示、3 道检查题</p></div><span class="tag">${status(l)}</span></a>`}).join('')}</div><section class="card section-space"><h2>有电脑时：第一次安装与运行</h2><ol><li>从 <a href="https://cran.r-project.org/" target="_blank" rel="noopener">R 官方网站</a>按系统下载并安装 R。你用 Windows 时选择 Windows → base。</li><li>再从 <a href="https://posit.co/download/rstudio-desktop/" target="_blank" rel="noopener">Posit 官方入口</a>获取适合系统的 RStudio Desktop。R 是计算环境，RStudio 是操作界面。</li><li>打开 RStudio，找到 Console，在提示符后输入 <code>2 + 3</code>，按 Enter。看到 <code>[1] 5</code>，第一次计算就成功了。</li><li>建立 R Script，在脚本写同样一行，通过 Run 执行，保存为 .R 文件。之后逐行学习，不要一开始整段粘贴运行。</li></ol><p><a href="R零基础_第一次练习.R" download>下载带中文注释的第一次练习.R</a></p><p class="small muted">这里提供操作指导，不会自动安装软件。手机上的逐行演示不是 R 解释器，也不会读取你的本地数据。</p></section><section class="card section-space"><h2>怎么知道真的学会了？</h2><p>能不看答案说出一行代码的作用；能改一个数并先猜输出；能在新脚本里重现同样结果。这比记住函数名字更重要。</p></section>`,'path')}
function rTrace(id){let l=lesson(id);if(!l?.rtrace){rStart();return}let step=0;shell(heading(l.title,'固定示例的逐行教学演示，不执行任意 R 代码。先预测，再打开解释。')+`<div class="grid grid-main"><section class="card"><div id="r-trace-content" aria-live="polite"></div></section><aside class="card"><h2>先猜这一行的结果</h2><label class="field">我的预测<textarea id="r-guess" placeholder="会得到一个数、一组数、一张表，还是只保存对象？">${esc(S.notes['rguess-'+id]||'')}</textarea></label><div class="actions"><button id="r-next" class="btn">看这一行的解释</button><button id="r-reset" class="btn secondary">从头演示</button></div><p class="small muted section-space">看过演示不自动算练习通过。去做题，再在电脑上改一个输入验证。</p>${link(id,'回到这一节')}<p class="section-space"><a href="#learn/${id}/practice">独立做 3 道题 →</a></p></aside></div>`,'path');function draw(){$('#r-trace-content').innerHTML=l.rtrace.map(([code,out,why],i)=>`<section class="reading-task"><strong>第 ${i+1} 行</strong><pre><code>${esc(code)}</code></pre>${i<step?`<div class="notice"><strong>结果 / 状态</strong><pre>${esc(out)}</pre><p>${esc(why)}</p></div>`:'<p class="muted">先猜会发生什么，再继续。</p>'}</section>`).join('');$('#r-next').disabled=step>=l.rtrace.length;$('#r-next').textContent=step>=l.rtrace.length?'已看完，去独立练习':'解释第 '+(step+1)+' 行'}$('#r-next').onclick=()=>{step++;draw()};$('#r-reset').onclick=()=>{step=0;draw()};$('#r-guess').oninput=e=>{S.notes['rguess-'+id]=e.target.value;save()};draw()}
function foundations(){shell(heading('基础补课','先学当前章节需要的基础，不要求把所有数学书读完。')+`<div class="route-list">${C.lessons.filter(l=>l.group==='基础补课').map(l=>`<a class="route-item" href="#learn/${l.id}"><div><strong>${l.title}</strong><p class="small muted">${l.method}</p></div><span class="tag">${status(l)}</span></a>`).join('')}</div>`,'path')}
function chapter(id){let ch=C.chapters.find(c=>c.id===Number(id));if(!ch){path();return}let ids=chapterLessons(ch),rs=C.resources.filter(r=>r.topics.some(t=>ids.includes(t)));shell(heading(`第 ${ch.id} 章 · ${ch.title}`,ch.objective)+`<div class="actions"><a href="#path">← 全课程目录</a><a class="btn secondary" href="#chaptercheck/${ch.id}">本章练习与查漏</a><a class="btn secondary" href="#resources/chapter-${ch.id}">本章公开资料（${rs.length}）</a></div><p class="notice section-space">${ch.basis}${ch.tentative?' 第十四章是否实施与具体要求，待教师确认。':''}</p><section class="card"><h2>先理解，再应试</h2><div class="grid grid-2"><div><h3>真正会用</h3><p>能说明输入、输出、目标、假设和一个失败情形。用一个新例子检验，不以看完作为完成。</p></div><div><h3>闭卷练习</h3><p>不看答案列出条件与公式，手算本章例题。错在符号就补先修，错在条件就比较反例。本站不把后续主题标成已确认考点。</p></div></div></section>${ch.sections.map(sec=>`<section class="card section-space"><span class="tag">${ch.id}.${sec.number}</span><h2>${sec.title}</h2><div class="grid">${sec.lessons.map(id=>{let l=lesson(id);return `<div class="outline-row"><div><strong>${l.title}</strong><p class="small muted">${l.method}</p><span class="tag gray">${status(l)}</span></div>${link(id,'打开学习')}</div>`}).join('')}</div></section>`).join('')}${ch.extras?.length?`<section class="card section-space"><h2>章标题延伸：非线性回归</h2>${ch.extras.map(id=>link(id)).join('')}</section>`:''}${ch.experiment?`<section class="card section-space"><h2>Python 扩展实验 · 选学</h2><p>第一次接触编程时，先走 <a href="#rstart">R 零基础路线</a>。下面 Python 代码可暂时跳过，不是学习本章理论的前提。</p><p>${ch.experiment.title}</p><p class="small muted">先预测输出，再在 Python + NumPy 环境中运行。手机可先逐行读；本页不会执行 Python。</p><details><summary>查看本章完整代码</summary><pre><code>${esc(ch.experiment.code)}</code></pre></details><div class="actions"><a href="全课程小实验.ipynb" download>下载 14 章 Notebook</a><a href="全课程小实验.py" download>下载 Python 脚本</a></div></section>`:''}<section class="card section-space"><h2>把知识用一次</h2><p>${ch.project}</p><label class="field">我的实验或思考记录<textarea id="chapter-note" rows="6" placeholder="问题 → 方法 → 结果 → 哪些结论不能推出">${esc(S.notes['chapter-'+ch.id]||'')}</textarea></label><p class="small muted">自动保存。这是应用记录，不自动冒充客观得分。</p>${ch.id<14?`<a class="btn secondary" href="#chapter/${ch.id+1}">查看下一章</a>`:''}</section>`,'path');$('#chapter-note').oninput=e=>{S.notes['chapter-'+ch.id]=e.target.value;save()}}
function chapterCheck(id){let ch=C.chapters.find(c=>c.id===Number(id));if(!ch){path();return}let qs=chapterLessons(ch).flatMap(id=>C.questions.filter(q=>q.lesson===id));shell(heading(`第 ${ch.id} 章 · 查漏练习`,'复用单元题库，逐题反馈，不是独立官方试卷。先不看笔记；答错后直接回到对应单元。')+`<p><a href="#chapter/${ch.id}">← 返回本章</a></p><section class="card">${qs.map(q=>quiz(q)).join('')}</section>`,'exam');bindQuiz()}
function courseCheck(){const qs=C.chapters.flatMap(ch=>{let ids=chapterLessons(ch),a=C.questions.filter(q=>ids.includes(q.lesson));return [a.find(q=>q.type==='number'),a.findLast(q=>q.transfer)].filter(Boolean).map(q=>({ch,q}))});shell(heading('全课程 28 题自测','每章一个计算检查、一个迁移检查。来自课程练习库；用于定位薄弱章，不代表考试命题或完整掌握。')+qs.map(({ch,q})=>`<section class="card section-space"><h2>第 ${ch.id} 章 · ${ch.title}</h2>${quiz(q)}</section>`).join(''),'exam');bindQuiz()}

function quiz(q,review=false){return `<form class="question" data-q="${q.id}" data-review="${review}"><fieldset><legend>${q.transfer?'【迁移】':''}${esc(q.prompt)}</legend>${q.type==='choice'?q.options.map((o,i)=>`<label class="option"><input type="radio" name="answer" value="${i}" required> ${esc(o)}</label>`).join(''):`<label class="field">你的计算结果<input name="answer" inputmode="decimal" placeholder="可填小数或分数，如 1/9" required autocomplete="off"></label>`}</fieldset><details class="hint"><summary>需要一点提示</summary><p>${esc(q.hint)}</p></details><button class="btn small-btn" type="submit">检查答案</button><div class="feedback" aria-live="polite"></div></form>`}
function numeric(v){v=String(v).trim();if(!v)return NaN;if(/^[+-]?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?$/i.test(v))return Number(v);if(/^[+-]?\d+(?:\.\d+)?\s*\/\s*[+-]?\d+(?:\.\d+)?$/.test(v)){let[a,b]=v.split('/').map(Number);return b?a/b:NaN}return NaN}
function bindQuiz(){document.querySelectorAll('form[data-q]').forEach(f=>{let hinted=false;f.querySelector('details').ontoggle=e=>{if(e.target.open)hinted=true};f.onsubmit=e=>{e.preventDefault();let q=qby(f.dataset.q),v=new FormData(f).get('answer'),n=numeric(v),ok=q.type==='choice'?String(q.answer)===v:Number.isFinite(n)&&Math.abs(n-q.answer)<=(q.tolerance||.005);if(v===null||!String(v).trim()){toast('请先作答');return}let previous=S.attempts.filter(a=>a.id===q.id).at(-1),review=f.dataset.review==='true'&&previous&&Date.now()-previous.time>=DAY;S.attempts.push({id:q.id,ok,time:Date.now(),hint:hinted,review:!!review,value:String(v)});save();f.querySelector('.feedback').innerHTML=`<strong>${ok?'答对了':'再检查一下'}</strong><p>${esc(q.explain)}</p>${hinted?'<p class="small">本次使用提示，记录为辅助练习。请之后独立复习。</p>':''}${!ok?`<p>本题重点：${esc(q.kind)}。${link(q.lesson,'回到这节的讲解')}</p>`:''}`;f.querySelector('.feedback').classList.toggle('wrong',!ok);f.querySelector('button').disabled=true;f.querySelectorAll('input').forEach(i=>i.disabled=true)}})}
function learn(id,tab='understand'){const l=lesson(id);if(!l){location.hash='path';return}S.seen[id]=S.seen[id]||Date.now();save();let body='';if(tab==='understand')body=`<h2>先说人话</h2>${l.intro.map(p=>`<p>${p}</p>`).join('')}<details><summary>还是抽象？换个小例子</summary><p>${l.simple}</p></details><div class="math">${l.formula}</div><h3>把符号逐个拆开</h3><div class="formula-parts">${Object.entries(l.terms).map(([k,v])=>`<details><summary>${esc(k)}</summary><p>${esc(v)}</p></details>`).join('')}</div><p class="notice">学习方法：${l.why}</p><a class="btn" href="#learn/${id}/worked">跟着做一个例子 →</a>`;
if(tab==='worked')body=`<h2>先尝试，再打开下一步</h2><p>${l.example}</p><label class="field">先写下你想从哪一步开始<textarea id="scratch" placeholder="不要求写对，先留下你的思路。">${esc(S.notes[id+'-scratch']||'')}</textarea></label>${l.steps.map(([h,t],i)=>`<details><summary>第 ${i+1} 步 · ${h}</summary><p>${t}</p></details>`).join('')}<p class="notice warn">容易踩的坑：${l.trap}</p><a class="btn" href="#learn/${id}/practice">不看答案，自己试一次 →</a>`;
if(tab==='practice')body=`<h2>独立练习</h2><p class="small muted">先尝试，不会再用提示。答完会解释理由；本节第 3 题检验迁移。</p>${l.questions.map(id=>quiz(qby(id))).join('')}`;
if(tab==='resources')body=lessonReading(l);
if(tab==='recall')body=`<h2>合上讲义，你能讲清楚吗？</h2><ul>${l.recall.map(t=>`<li>${t}</li>`).join('')}</ul><label class="field">用自己的话解释，并写下仍不懂的一处<textarea id="recall" rows="6" placeholder="这是什么 → 为什么这样做 → 什么时候不能用">${esc(S.notes[id]||'')}</textarea></label><p class="small muted">文字自动保存在本机；自述不自动计入掌握率。</p><a class="btn" href="#today">回到今日安排</a>`;
shell(heading(l.title,`${l.group} · ${l.method}`)+`<div class="tabs">${[['understand','① 看懂'],['worked','② 跟着做'],['practice','③ 独立做'],['recall','④ 讲出来'],['resources','⑤ 继续学']].map(([t,n])=>`<a class="tab ${tab===t?'active':''}" href="#learn/${id}/${t}">${n}</a>`).join('')}</div><div class="grid grid-main"><article class="card lesson-body">${body}</article><aside class="grid"><section class="card"><h3>我卡在哪里？</h3><p class="small">符号看不懂，先回到基础；运算卡住，展开具体数字再试。</p><div class="actions">${(l.pre.length?l.pre:['mean']).map(i=>link(i)).join('')}${link('rcode','代码看不懂')}</div>${l.rtrace?`<p><a class="btn" href="#rtrace/${l.id}">逐行演示 · 先猜再看</a></p>`:''}${l.lab?`<a class="btn section-space" href="#labs/${l.lab}">用互动实验理解</a>`:''}</section><section class="card soft"><h3>本节对应</h3><p class="small">${l.source}</p>${l.sourceUrl?`<p><a target="_blank" rel="noopener" href="${l.sourceUrl}">核对原理来源 ↗</a></p>`:''}<div class="actions">${(l.chapters||[]).map(n=>`<a href="#chapter/${n}">第 ${n} 章</a>`).join('')}</div><span class="tag">${status(l)}</span><p class="small">先读条件，再代公式。练习通过后，隔天再检验。</p></section></aside></div>`,'path');bindQuiz();if($('#recall'))$('#recall').oninput=e=>{S.notes[id]=e.target.value;save()};if($('#scratch'))$('#scratch').oninput=e=>{S.notes[id+'-scratch']=e.target.value;save()}}
function diagnostic(){shell(heading('8 题基础诊断','约 5 分钟。不会就选“暂时不会”，这比猜对更有用。')+`<form id="diagnostic" class="card">${C.diagnostic.map((q,k)=>`<fieldset class="question"><legend>${k+1}. ${q.prompt}</legend>${q.options.map((t,i)=>`<label class="option"><input type="radio" name="${q.id}" value="${i}" required> ${t}</label>`).join('')}</fieldset>`).join('')}<button class="btn">生成补课建议</button></form>`,'today');$('#diagnostic').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),weak=C.diagnostic.filter(q=>String(q.answer)!==f.get(q.id)).map(q=>q.lesson);S.diagnosis={time:Date.now(),weak};save();shell(heading('从这些缺口开始','这只是每个主题一道题的初筛，不是掌握证明。')+`<section class="card"><p>本次 ${8-weak.length}/8 道正确。${weak.length?'建议先补下面的基础，再进入课程。':'可以从第一讲开始，但仍用独立练习验证。'}</p>${C.diagnostic.map(q=>`<p><strong>${weak.includes(q.lesson)?'需补课':'初筛通过'} · ${lesson(q.lesson).title}</strong><br>${q.explain}</p>${weak.includes(q.lesson)?link(q.lesson):''}`).join('')}<p>${link(weak[0]||'model','开始推荐单元')}</p></section>`,'today')}}
function review(){let qs=due();shell(heading('错题与间隔复习','答错立即纠正；独立答对后隔 1 天复习，通过后隔 3 天再测。同一天重做不算间隔复习。')+`<section class="card"><h2>${qs.length?`${qs.length} 道题等待你`:'目前没有到期题'}</h2><p class="muted">${qs.length?'先看题自己回答，再看解释。题目可能重复，因此“复习通过”只表示这组练习的表现。':'先完成一个单元的练习。之后你会在这里看到错题和到期复习。'}</p>${qs.map(q=>quiz(q,true)).join('')}${!qs.length?link(next().id,'去学今天的一节'):''}</section>`,'review');bindQuiz()}
function lessonReading(l){let rs=C.resources.filter(r=>r.topics.includes(l.id));return `<h2>把这一节学扎实</h2><p>每天最多选一个补充任务。先完成本页例题，再打开外部材料。看完要回到独立练习，不能用收藏代替学习。</p>${l.code?`<h3>最小 R 实验</h3><pre><code>${esc(l.code)}</code></pre><p class="small muted">在 R 环境中运行；本页不执行代码。先预测输出，再改一个输入并解释变化。</p>`:''}${rs.length?rs.map(r=>`<section class="reading-task"><span class="tag">${r.type}</span><h3>${r.name}</h3><p>${r.task}</p><p><strong>学会的证据：</strong>${r.finish}</p><p class="small muted">${r.note}</p><div class="actions"><a href="${r.url}" target="_blank" rel="noopener">读指定资料 ↗</a><a href="${r.repo}" target="_blank" rel="noopener">看代码来源 ↗</a></div></section>`).join(''):`<p>先完成本节例题与迁移题。${l.sourceUrl?`<a href="${l.sourceUrl}" target="_blank" rel="noopener">再核对原始方法说明 ↗</a>`:'<a href="#resources">按需要选择基础补充资源</a>'}</p>`}<h3>留下一个可检查的结果</h3><p>写出：我修改了什么 → 结果怎样变 → 哪条原理解释这个变化。把记录保存在“讲出来”页。</p>`}
function resources(filter=''){const selected=filter.startsWith('chapter-')?C.resources.filter(r=>r.topics.some(t=>chapterLessons(C.chapters[Number(filter.slice(8))-1]||C.chapters[0]).includes(t))):filter?C.resources.filter(r=>r.topics.includes(filter)):C.resources;shell(heading('公开资料 · 带着问题去学','先用内置讲解；只在具体卡点上补充，不需要同时学完这些书。')+`<p><a href="#resources">全部 ${C.resources.length} 项</a> · ${filter?'已按关联章节筛选':'中文入门 → 动手复现 → 原理推导 → 研究阅读'}</p><div class="grid grid-2">${selected.map(r=>`<section class="card"><span class="tag">${r.type}</span><h2>${r.name}</h2><p><strong>什么时候看：</strong>${r.when}</p><p><strong>只做这件事：</strong>${r.task}</p><p><strong>完成标准：</strong>${r.finish}</p><p class="small muted">${r.note}<br>语言：${r.language||'中文/英文'} · 链接核对：${r.checked||'2026-09-26'}</p><div class="actions"><a target="_blank" rel="noopener" href="${r.url}">打开资源 ↗</a><a target="_blank" rel="noopener" href="${r.repo}">GitHub 仓库 ↗</a></div></section>`).join('')}</div><section class="card section-space"><h2>学习数据备份</h2><p>进度、笔记和测验仅保存在当前设备的浏览器。换手机或清理浏览器前请导出；GitHub 不会同步你的学习记录。</p><button class="btn" id="export">导出 JSON 备份</button><label class="field section-space">从备份恢复（将替换当前记录）<input id="import" type="file" accept="application/json,.json"></label><p class="small muted">${C.referenceNote}</p><a href="https://github.com/sallowayma-git/IELTS-practice" target="_blank" rel="noopener">流程参考：IELTS-practice</a></section>`,'resources');$('#export').onclick=()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.href=u;a.download='回归练习室-学习备份.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};$('#import').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{if(f.size>2e6)throw Error();const s=validate(JSON.parse(await f.text()));if(!s)throw Error();if(!confirm('恢复备份会替换本机当前记录。已导出需要保留的记录吗？'))return;S=s;save();toast('备份恢复成功')}catch{toast('备份无效或超过 2 MB，当前记录未变更。')}}}
const labsList={mean:'均值与散布',ols:'亲手找到回归线',sampling:'重复抽样与标准误',matrix:'矩阵乘法逐项算',test:'t 检验与区间',prediction:'均值区间与个体预测',collinear:'共线性放大不稳定',overfit:'训练误差与泛化',code:'R 代码逐行追踪',shrink:'正则化收缩',pcaview:'PCA 投影',threshold:'分类阈值',attention:'注意力权重',rankview:'LoRA 参数'};
const avg=a=>a.reduce((s,v)=>s+v,0)/a.length,sum=a=>a.reduce((s,v)=>s+v,0),fmt=n=>Number.isFinite(n)?Number(n.toFixed(4)).toString():'不可计算';
function slider(id,label,min,max,value,step=1){return `<label class="range-field">${label}：<output id="${id}-v">${value}</output><input type="range" id="${id}" min="${min}" max="${max}" value="${value}" step="${step}"></label>`}
function chart(points,line,extra=[]){let all=[...points,...line,...extra],xs=all.map(p=>p[0]),ys=all.map(p=>p[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);let xx=x=>45+(x-xmin)/(xmax-xmin||1)*505,yy=y=>250-(y-ymin)/(ymax-ymin||1)*220;return `<svg viewBox="0 0 580 290" role="img" aria-label="散点与拟合曲线；数值和解释见下方"><path d="M45 20V250H555" stroke="#94a3b8" fill="none"/><text x="45" y="276" font-size="12">x = ${fmt(xmin)}</text><text x="487" y="276" font-size="12">${fmt(xmax)}</text><text x="3" y="25" font-size="11">${fmt(ymax)}</text><text x="3" y="248" font-size="11">${fmt(ymin)}</text>${line.length?`<polyline points="${line.map(p=>`${xx(p[0])},${yy(p[1])}`).join(' ')}" fill="none" stroke="#275bd7" stroke-width="3"/>`:''}${points.map(p=>`<circle cx="${xx(p[0])}" cy="${yy(p[1])}" r="5" fill="#153054"/>`).join('')}${extra.map(p=>`<circle cx="${xx(p[0])}" cy="${yy(p[1])}" r="3" fill="#d18428"/>`).join('')}</svg>`}
function solve(a,b){a=a.map((r,i)=>[...r,b[i]]);let n=b.length;for(let i=0;i<n;i++){let k=i;for(let j=i+1;j<n;j++)if(Math.abs(a[j][i])>Math.abs(a[k][i]))k=j;if(Math.abs(a[k][i])<1e-12)return null;[a[i],a[k]]=[a[k],a[i]];let d=a[i][i];for(let t=i;t<=n;t++)a[i][t]/=d;for(let j=0;j<n;j++)if(i!==j){d=a[j][i];for(let t=i;t<=n;t++)a[j][t]-=d*a[i][t]}}return a.map(r=>r[n])}
function labs(id='ols'){if(['shrink','pcaview','threshold','attention','rankview'].includes(id)){advancedLab(id);return}if(!labsList[id])id='ols';let controls='',intro='',lessonId='ols';if(id==='mean'){controls=slider('a','第一个数',0,12,2)+slider('b','第二个数',0,12,4)+slider('c','第三个数',0,12,6);intro='先预测：把最大值继续调大，均值与平方和会怎样变？';lessonId='spread'}
if(id==='ols'){controls=slider('a','截距 a',-3,6,0,.1)+slider('b','斜率 b',-1,4,1,.05)+'<button class="btn secondary" id="best">对照最小二乘解</button>';intro='先自己拖动，让点到直线的竖直误差平方和最小，再对照最优解。'}
if(id==='sampling'){controls=slider('n','每次样本量 n',2,100,10)+slider('sigma','个体标准差 σ',1,10,4)+ '<button class="btn secondary" id="resample">重新抽取 100 组样本</button>';intro='总体均值固定为 5。先预测：增大 n 后，样本均值会更集中还是更分散？';lessonId='se'}
if(id==='matrix'){controls=slider('x','样本特征 x',-5,5,2)+slider('a','截距 β₀',-5,5,1)+slider('b','斜率 β₁',-5,5,3);intro='一行样本乘一列系数，得到一个预测值。先口算，再拖动核对。';lessonId='matrix'}
if(id==='test'){controls=slider('b','估计系数 b',-3,3,1,.05)+slider('se','标准误 SE',.1,2,.5,.05);intro='固定自由度 18，双侧 5% 临界值 2.1009，检验 H₀: β=0。先预测增大 SE 会怎样。';lessonId='test'}
if(id==='prediction'){controls=slider('x','新位置 x₀',-5,5,0,.1);intro='固定 n=25，x̄=0，SXX=50，残差标准差 s=2，拟合均值 3+x₀。自由度23，t临界值2.0687。';lessonId='prediction'}
if(id==='collinear'){controls=slider('eps','两列的区别 ε',0,2,.5,.01)+slider('perturb','第一个 y 的扰动',-.3,.3,0,.01);intro='X₂=X₁+εz。先把 ε 调小，再微调一个 y，观察系数是否大幅变化。';lessonId='collinear'}
if(id==='overfit'){controls=slider('degree','多项式次数',1,8,1);intro='固定 12 个训练点和 40 个留出点，拟合带噪声的曲线。改变复杂度，比较两种误差；这一次模拟不保证每级验证误差都变大。';lessonId='overfit'}
if(id==='code'){controls='<button class="btn" id="nextline">执行下一行（教学追踪）</button><button class="btn secondary" id="resetcode">从头开始</button>';intro='这是预先校验的逐行教学演示，不是在线 R 解释器。每一行先猜输出，再继续。';lessonId='rcode'}
shell(heading(labsList[id],intro)+`<div class="pill-row">${Object.entries(labsList).map(([k,v])=>`<a class="pill ${k===id?'active':''}" href="#labs/${k}">${v}</a>`).join('')}</div><div class="grid grid-main section-space"><section class="card"><div id="labresult" aria-live="polite"></div></section><aside class="card"><h2>动手改变一个量</h2>${controls}<div class="divider"></div><label class="field">我的预测和观察<textarea id="labnote" placeholder="我原以为……改变后发现……原因可能是……">${esc(S.notes['lab-'+id]||'')}</textarea></label>${link(lessonId,'回到对应知识点')}</aside></div>`,'labs');let seed=137,line=0;function rnd(){seed=(seed*1664525+1013904223)>>>0;return (seed+.5)/4294967296}function normal(){return Math.sqrt(-2*Math.log(rnd()))*Math.cos(2*Math.PI*rnd())}function val(k){return Number($('#'+k).value)}
function update(){document.querySelectorAll('input[type=range]').forEach(e=>$('#'+e.id+'-v').textContent=e.value);let html='';if(id==='mean'){let a=[val('a'),val('b'),val('c')],m=avg(a),sq=sum(a.map(x=>(x-m)**2));html=chart(a.map((y,i)=>[i+1,y]),[[1,m],[3,m]])+`<div class="math">平均数 = ${fmt(m)}<br>SXX = ${fmt(sq)}<br>样本方差 = SXX / 2 = ${fmt(sq/2)}</div><p>每个数减均值：${a.map(v=>fmt(v-m)).join('，')}。这些差的和仍为 0。</p>`}
if(id==='ols'){let p=[[0,1],[1,2],[2,2],[3,4],[4,6]],a=val('a'),b=val('b'),sse=sum(p.map(([x,y])=>(y-a-b*x)**2));html=chart(p,[[0,a],[4,a+4*b]])+`<div class="math">ŷ = ${fmt(a)} + ${fmt(b)}x<br>误差平方和 RSS = ${fmt(sse)}</div><p>同一批点中，RSS 越小越贴近。最小二乘解为 a=0.6，b=1.2，RSS=1.6。拟合好不等于因果关系。</p>`}
if(id==='sampling'){let n=val('n'),s=val('sigma'),means=Array.from({length:100},()=>5+s*sum(Array.from({length:n},normal))/n),m=avg(means),sd=Math.sqrt(sum(means.map(x=>(x-m)**2))/99);html=chart(means.map((y,i)=>[i+1,y]),[[1,5],[100,5]])+`<div class="math">理论 SE = σ/√n = ${fmt(s/Math.sqrt(n))}<br>这 100 次均值的样本标准差 = ${fmt(sd)}</div><p>一个点表示一次抽样得到的均值，不是原始观测。模拟结果会波动，不必恰好等于理论值。总体均值始终是 5。</p>`}
if(id==='matrix'){let x=val('x'),a=val('a'),b=val('b');html=`<h2>行 × 列 → 一个数</h2><div class="math">[ 1　${x} ] × [ ${a}　${b} ]ᵀ<br>= 1×${a} + ${x}×${b}<br>= ${a+x*b}</div><p>维度：(1×2) × (2×1) = (1×1)。前面的 1 是截距列。</p><p>换成 n 个样本，就是 Xβ；每一行重复同样的乘加。</p>`}
if(id==='test'){let b=val('b'),se=val('se'),t=b/se,c=2.100922;html=`<div class="math">t = (${fmt(b)} − 0) / ${fmt(se)} = ${fmt(t)}<br>95% CI = [${fmt(b-c*se)}, ${fmt(b+c*se)}]</div><p class="notice">${Math.abs(t)>c?'|t| 大于临界值，拒绝 H₀；区间不含 0。':'|t| 不超过临界值，不拒绝 H₀；区间包含 0。'}</p><p>不拒绝不代表证明 β=0。这里使用正态误差线性模型的 t 推断条件；没有显示未经计算的 p 值。</p>`}
if(id==='prediction'){let x=val('x'),mu=3+x,h=1/25+x*x/50,c=2.0686576*2,ci=c*Math.sqrt(h),pi=c*Math.sqrt(1+h);html=`<div class="math">预测中心 = ${fmt(mu)}<br>均值 CI：[${fmt(mu-ci)}, ${fmt(mu+ci)}]<br>个体 PI：[${fmt(mu-pi)}, ${fmt(mu+pi)}]</div><div class="bar-row">均值半宽 <progress value="${ci}" max="6"></progress> ${fmt(ci)}</div><div class="bar-row">个体半宽 <progress value="${pi}" max="6"></progress> ${fmt(pi)}</div><p>位置越远离 x̄，杠杆 h 越大。个体预测还要加一个新误差，因此更宽。这里只演示固定模型下的公式，不保证外推合理。</p>`}
if(id==='collinear'){let e=val('eps'),d=val('perturb'),x=[-2,-1,0,1,2],z=[1,-2,2,-2,1],u=x.map((v,i)=>v+e*z[i]),y=x.map((v,i)=>1+2*v+(i===0?d:0)),my=avg(y),xx=sum(x.map(v=>v*v)),uu=sum(u.map(v=>v*v)),xu=sum(x.map((v,i)=>v*u[i])),det=xx*uu-xu*xu;if(det<1e-10)html='<div class="notice warn">ε=0：两列完全相同。OLS 仍有最小值，但两个斜率无法唯一拆开，VIF 发散。</div>';else{let xy=sum(x.map((v,i)=>v*(y[i]-my))),uy=sum(u.map((v,i)=>v*(y[i]-my))),b1=(xy*uu-uy*xu)/det,b2=(uy*xx-xy*xu)/det;html=`<div class="math">b₁ = ${fmt(b1)}<br>b₂ = ${fmt(b2)}<br>b₁+b₂ = ${fmt(b1+b2)}<br>VIF = ${fmt(1/(1-xu*xu/xx/uu))}</div><p>ε=${e}，扰动=${d}。高度相关时，单个系数容易大幅变化，组合预测却可能仍相近。</p>`}}
if(id==='overfit'){let degree=val('degree'),xs=Array.from({length:12},(_,i)=>-1+2*i/11),ys=xs.map((x,i)=>Math.sin(2.6*x)+.25*Math.sin(i*7+1)),test=Array.from({length:40},(_,i)=>{let x=-.98+1.96*i/39;return [x,Math.sin(2.6*x)+.25*Math.cos(i*5+2)]}),design=xs.map(x=>Array.from({length:degree+1},(_,k)=>x**k)),a=Array.from({length:degree+1},(_,j)=>Array.from({length:degree+1},(_,k)=>sum(design.map(r=>r[j]*r[k])))),b=Array.from({length:degree+1},(_,j)=>sum(design.map((r,i)=>r[j]*ys[i]))),coef=solve(a,b),pred=x=>sum(coef.map((b,j)=>b*x**j)),train=avg(xs.map((x,i)=>(pred(x)-ys[i])**2)),testM=avg(test.map(([x,y])=>(pred(x)-y)**2));html=chart(xs.map((x,i)=>[x,ys[i]]),Array.from({length:101},(_,i)=>{let x=-1+i/50;return[x,pred(x)]}),test)+`<div class="math">训练 MSE = ${fmt(train)}<br>留出 MSE = ${fmt(testM)}</div><p>蓝黑点是训练数据，橙点是留出数据，蓝线是拟合曲线。不能用训练误差代替泛化表现；反复看留出结果调参，也会让留出集不再独立。</p>`}
if(id==='code'){let lines=[['x <- c(1, 2, 3)','建立数值向量 x：1, 2, 3'],['y <- c(2, 4, 5)','建立响应向量 y：2, 4, 5'],['d <- data.frame(x, y)','得到 3 行、2 列的数据框'],['fit <- lm(y ~ x, data = d)','拟合 y 对 x 的含截距最小二乘回归'],['coef(fit)','(Intercept) = 0.6667；x = 1.5'],['predict(fit, data.frame(x = 4))','输出 6.6667。这是外推，解释要谨慎。']];html=`<h2>输入 → 运算 → 输出</h2>${lines.map(([c,t],i)=>`<div class="trace-line"><pre><code>${esc(c)}</code></pre><p class="trace-explain">${i<line?t:'先猜这一行做什么，再执行下一行。'}</p></div>`).join('')}<p class="small muted">已追踪 ${line}/6 行。演示数据已校验，不能执行你自己的 R 代码。</p>`;$('#nextline').disabled=line>=6}
$('#labresult').innerHTML=html}
document.querySelectorAll('input[type=range]').forEach(e=>e.oninput=update);$('#labnote').oninput=e=>{S.notes['lab-'+id]=e.target.value;save()};if($('#best'))$('#best').onclick=()=>{$('#a').value=.6;$('#b').value=1.2;update()};if($('#resample'))$('#resample').onclick=update;if($('#nextline'))$('#nextline').onclick=()=>{line++;update()};if($('#resetcode'))$('#resetcode').onclick=()=>{line=0;update()};update()}
function advancedLab(id){const titles={shrink:'正则化：同一信号怎样被收缩',pcaview:'PCA：转动投影方向',threshold:'分类阈值：漏报与误报',attention:'注意力：得分变成权重',rankview:'低秩更新：参数预算'};let controls='',intro='',unit='ridge';if(id==='shrink'){controls=slider('z','未收缩信号 z',-5,5,3,.1)+slider('lam','惩罚强度 λ',0,5,1,.1);intro='先预测：λ 增大时，哪个估计会直接变成 0？';unit='lasso'}if(id==='pcaview'){controls=slider('angle','投影方向角度（度）',-90,90,0,1)+'<button class="btn secondary" id="pca-best">找到最大方差方向</button>';intro='固定中心化点云。旋转蓝线，比较投影方差与丢失的信息。';unit='pca'}if(id==='threshold'){controls=slider('cut','判正阈值',0,1,.5,.05);intro='固定 10 个概率与真实标签。阈值下降时，会找回更多正类，还是产生更多误报？';unit='classmetrics'}if(id==='attention'){controls=slider('score1','第一项匹配得分',-4,4,0,.1)+slider('score2','第二项匹配得分',-4,4,1,.1);intro='两项 value 固定为 2 和 6。拖动匹配得分，看 softmax 怎样改变加权输出。';unit='transformer'}if(id==='rankview'){controls=slider('rank','更新 rank',1,64,4,1);intro='一个 64×64 原权重矩阵保持冻结。改变 LoRA 中间维数，核对 BA 的形状与参数。';unit='lora'}
shell(heading(titles[id],intro)+`<div class="pill-row">${Object.entries(labsList).map(([k,v])=>`<a class="pill ${k===id?'active':''}" href="#labs/${k}">${v}</a>`).join('')}</div><div class="grid grid-main section-space"><section class="card"><div id="labresult" aria-live="polite"></div></section><aside class="card"><h2>先预测，再拖动</h2>${controls}<label class="field">我的观察<textarea id="adv-note">${esc(S.notes['lab-'+id]||'')}</textarea></label>${link(unit,'回到讲解与练习')}</aside></div>`,'labs');let val=k=>Number($('#'+k).value);const raw=[[-3,-2],[-2,-.6],[-.5,-1],[1,.8],[2,1.6],[3,1.2]],mx=avg(raw.map(p=>p[0])),my=avg(raw.map(p=>p[1])),pts=raw.map(([x,y])=>[x-mx,y-my]);function draw(){document.querySelectorAll('input[type=range]').forEach(e=>$('#'+e.id+'-v').textContent=e.value);let h='';if(id==='shrink'){let z=val('z'),l=val('lam'),r=z/(1+l),a=Math.sign(z)*Math.max(Math.abs(z)-l,0);h=`<h2>三个估计并排看</h2><div class="math">未惩罚：${fmt(z)}<br>Ridge：${fmt(r)}<br>Lasso：${fmt(a)}</div><p>本实验的一维目标分别为：½(z−b)²，½(z−b)²+λb²/2，½(z−b)²+λ|b|。</p><p>这里的 Ridge 解是 z/(1+λ)，Lasso 解是软阈值。多维相关设计下不能直接把这个软阈值逐个套在 OLS 系数上。</p>`}if(id==='pcaview'){let t=val('angle')*Math.PI/180,c=Math.cos(t),s=Math.sin(t),pro=pts.map(([x,y])=>x*c+y*s),variance=sum(pro.map(x=>x*x))/(pts.length-1),total=sum(pts.map(([x,y])=>x*x+y*y))/(pts.length-1);h=chart(pts,[[-4*c,-4*s],[4*c,4*s]])+`<div class="math">投影样本方差 = ${fmt(variance)}<br>保留比例 = ${fmt(variance/total*100)}%<br>正交重建平方误差 = ${fmt((total-variance)*(pts.length-1))}</div><p>最大化保留方差等价于在一维正交投影中最小化重建平方误差。此图按数据范围绘制，横纵轴尺度未必相同；方向角度按原数据坐标计算。</p>`}if(id==='threshold'){let p=[.05,.12,.2,.32,.42,.55,.65,.75,.85,.95],y=[0,0,1,0,1,0,1,1,0,1],c=val('cut'),tp=0,fp=0,tn=0,fn=0;p.forEach((a,i)=>{if(a>=c)y[i]?tp++:fp++;else y[i]?fn++:tn++});h=`<h2>混淆矩阵</h2><div class="grid grid-2"><p>TP 真阳性：${tp}</p><p>FP 误报：${fp}</p><p>FN 漏报：${fn}</p><p>TN 真阴性：${tn}</p></div><div class="math">Precision = ${tp+fp?fmt(tp/(tp+fp)):'未定义（没有判正）'}<br>Recall = ${fmt(tp/(tp+fn))}<br>Accuracy = ${fmt((tp+tn)/10)}</div><p>概率：${p.join('，')}<br>真值：${y.join('，')}</p><p>先说清哪种错误代价高，再用验证集选阈值。不要反复在最终测试集上调整。</p>`}if(id==='attention'){let a=val('score1'),b=val('score2'),m=Math.max(a,b),ea=Math.exp(a-m),eb=Math.exp(b-m),w=ea/(ea+eb);h=`<div class="math">第一项权重 = ${fmt(w)}<br>第二项权重 = ${fmt(1-w)}<br>输出 = 2×${fmt(w)} + 6×${fmt(1-w)}<br>= ${fmt(2*w+6*(1-w))}</div><p>两个匹配得分相同时，权重各为 1/2。给两项得分同时加同一个常数，不改变权重。</p><p>这里只拆解一个查询的加权汇总，并非完整 Transformer 训练。权重不自动等同于因果重要性。</p>`}if(id==='rankview'){let r=val('rank'),count=128*r;h=`<div class="math">B：64×${r}；A：${r}×64<br>BA：64×64<br>可训练因子参数 = ${count}<br>完整矩阵参数 = 4096<br>因子 / 完整 = ${fmt(count/4096*100)}%</div><p>当 r 较大时，因子参数甚至不再节省。低秩更新有用的前提是所需变化能用较小 r 表达。</p><p>冻结主干仍要保存和计算；参数比例不是实际显存或推理速度比例。</p>`}$('#labresult').innerHTML=h}
document.querySelectorAll('input[type=range]').forEach(e=>e.oninput=draw);$('#adv-note').oninput=e=>{S.notes['lab-'+id]=e.target.value;save()};if($('#pca-best'))$('#pca-best').onclick=()=>{let xx=sum(pts.map(p=>p[0]**2)),yy=sum(pts.map(p=>p[1]**2)),xy=sum(pts.map(p=>p[0]*p[1]));$('#angle').value=Math.atan2(2*xy,xx-yy)/2*180/Math.PI;draw()};draw()}

function examQuestions(version){let b=version==='B',q=[],add=(id,prompt,options,answer,points,unit,explain,tolerance=.01)=>q.push({id,prompt,options,answer,points,unit,explain,tolerance});
add('e1','含截距的设计矩阵 X 有 40 行、4 列。自变量个数是？',['4','3','40'],1,4,'matrix','截距占一列，所以自变量有 3 个。');
add('e2','下列哪项表示回归系数估计无偏？',['每次估计等于真值','重复抽样的期望等于真值','方差为 0'],1,4,'unbiased','无偏是关于重复抽样期望的性质。');
add('e3','同一新位置下，个体预测区间通常比均值置信区间更宽，主要因为？',['个体多一个新误差','区间置信度必然更大','样本量必然更小'],0,4,'prediction','个体预测方差中多出 σ²。');
add('e4','两自变量几乎完全线性相关时，最直接的问题是？',['系数可能很不稳定','RSS 必然不存在最小值','预测一定完全错误'],0,4,'collinear','共线性使系数估计方差增大；完全相关时不唯一。');
[['所有含截距 OLS 回归的残差和为 0。',true,'residual','由截距列对应的正规方程得到。'],['不拒绝 H₀ 就证明 H₀ 为真。',false,'test','证据不足不是证明原假设正确。'],['加入自变量后，训练 RSS 不会上升（模型嵌套且使用相同样本的 OLS）。',true,'overfit','旧模型的拟合值仍在新的可选空间内。'],['方差 Var(3U) 等于 3Var(U)。',false,'cov','应为 9Var(U)。'],['任意总体和任意样本量下，回归系数 t 统计量都精确服从 t 分布。',false,'test','精确有限样本 t 推断需要相应线性正态模型条件。']].forEach(([p,a,u,e],i)=>add('e'+(i+5),p,['正确','错误'],a?0:1,2,u,e));
let xb=b?3:2,yb=b?7:5,sxx=b?8:10,sxy=b?12:20,syy=b?23:50,slope=sxy/sxx,intercept=yb-slope*xb,rss=syy-sxy*sxy/sxx;
add('e10a',`【OLS 14 分·第1项4分】给定 x̄=${xb}, ȳ=${yb}, SXX=${sxx}, SXY=${sxy}, SYY=${syy}。求斜率。`,null,slope,4,'ols','b₁=SXY/SXX。');
add('e10b','【第2项4分】用上一题数据求截距。',null,intercept,4,'ols',`b₀=ȳ−b₁x̄=${intercept}。`);
add('e10c','【第3项3分】用同一组数据求 RSS。',null,rss,3,'r2',`RSS=SYY−SXY²/SXX=${rss}。`);
add('e10d','【第4项3分】用同一组数据求 R²。',null,1-rss/syy,3,'r2','R²=1−RSS/SYY。');
let beta=b?1.2:1,se=b?.4:.25,c=2.1;
add('e11a',`【推断 14 分·第1项4分】估计斜率=${beta}，SE=${se}，检验 H₀:β=0，给定双侧临界值2.1。求 t。`,null,beta/se,4,'test','t=(估计−原假设值)/SE。');
add('e11b','【第2项4分】在同样条件下是否拒绝 H₀？',['拒绝','不拒绝'],0,4,'test','|t|>2.1，拒绝 H₀。');
add('e11c','【第3项6分】按给定临界值计算置信区间下界。',null,beta-c*se,6,'ci','下界=估计−2.1×SE。');
let v1=b?4:9,v2=b?9:4,cov=b?1:2;
add('e12a',`【多元回归 16 分·第1项6分】Var(b₁)=${v1}, Var(b₂)=${v2}, Cov(b₁,b₂)=${cov}。求 Var(b₁−b₂)。`,null,v1+v2-2*cov,6,'contrast','Var(b₁−b₂)=Var(b₁)+Var(b₂)−2Cov(b₁,b₂)。');
add('e12b',`【第2项5分】另一个辅助回归的 R²=${b?.9:.8}。求 VIF。`,null,b?10:5,5,'collinear','VIF=1/(1−R²)。');
add('e12c','【第3项5分】把含截距多元回归的所有自变量中心化后，新截距等于？',['0','响应样本均值','原截距必然不变'],1,5,'center','所有自变量均值变成 0，回归曲面通过样本均值点。');
let n=b?16:25,s=b?4:2;
add('e13a',`【预测 16 分·第1项6分】简单回归在 x₀=x̄ 处，n=${n}，残差标准差 s=${s}。求均值估计标准误。`,null,s/Math.sqrt(n),6,'prediction','x₀=x̄ 时 h=1/n，SE均值=s/√n。');
add('e13b','【第2项5分】同一位置的个体预测标准误是多少？',null,s*Math.sqrt(1+1/n),5,'prediction','SE预测=s√(1+1/n)。');
add('e13c','【第3项5分】把预测位置移离 x̄，在模型参数和置信度不变时，两种区间一般？',['都变窄','都变宽','一个变宽一个变窄'],1,5,'prediction','两者的杠杆项都增加。');return q}
function exam(){const e=S.exam;if(e&&!e.submitted){examRun();return}shell(heading('课程模拟测验','自编练习 · 当前第 1—3 讲 · 60 分钟 · 满分 100 分')+`<section class="card"><h2>先检验，再补缺口</h2><p><a class="btn secondary" href="#coursecheck">全课程 28 题查漏</a> <a href="#path">按 14 章练习 →</a></p><p>按大纲中的题型比例设计：选择 16 分、判断 10 分、计算与推理 74 分。不是官方试卷，也不代表已确认的完整期中考试范围。</p><p>计算支持小数与分数。自动判分 86 分；最后一道证明题 14 分采用明确评分要点自评，单独展示。相近数值按绝对误差 0.01 判定。</p><p class="notice warn">开始后计时持续，刷新不会重置。到时自动交卷。建议准备草稿纸或手机笔记，不看讲解做一遍。</p><div class="actions"><button class="btn" id="exam-a">开始 A 卷</button><button class="btn secondary" id="exam-b">开始 B 卷（变式）</button></div></section>${e?.submitted?examReport(e):''}<section class="card section-space"><h2>历史记录</h2>${S.history.length?S.history.map(h=>`<p>${new Date(h.time).toLocaleString('zh-CN')} · ${esc(h.version)} 卷 · 自动判分 ${h.score}/86${h.manual!=null?' · 自评 '+h.manual+'/14':''}</p>`).join(''):'<p class="muted">尚未交卷。练完基础再试，不必急着刷整卷。</p>'}</section>`,'exam');['a','b'].forEach(v=>$('#exam-'+v).onclick=()=>{S.exam={version:v.toUpperCase(),start:Date.now(),end:Date.now()+3600000,answers:{},proof:'',submitted:false};save();examRun()});bindManual()}
function examRun(){const e=S.exam,qs=examQuestions(e.version);shell(heading(`${e.version} 卷 · 专心完成一轮`,'不会的先跳过。输入自动保存到本机，返回此页可继续。')+`<div class="exam-header"><strong>剩余 <span id="timer"></span></strong><span>自动判分 86 + 证明自评 14</span></div><form id="exam-form" class="card">${qs.map((q,i)=>`<fieldset class="question"><legend>${i+1}. ${q.prompt}</legend>${q.options?q.options.map((t,k)=>`<label class="option"><input type="radio" name="${q.id}" value="${k}" ${String(e.answers[q.id])===String(k)?'checked':''}> ${t}</label>`).join(''):`<label class="field">计算结果<input name="${q.id}" inputmode="decimal" value="${esc(e.answers[q.id]||'')}" placeholder="可留空，稍后返回"></label>`}</fieldset>`).join('')}<label class="field"><strong>证明题（14 分）</strong>设 y=Xβ+ε，X 满列秩且 E(ε|X)=0。证明 OLS 系数条件无偏，并说明哪一步用到满列秩。<textarea name="proof" rows="7" placeholder="写出估计式 → 代入模型 → 取条件期望 → 说明条件">${esc(e.proof)}</textarea></label><button class="btn" type="submit">交卷并查看补课建议</button></form>`,'exam');$('#exam-form').oninput=ev=>{if(ev.target.name==='proof')e.proof=ev.target.value;else if(ev.target.name)e.answers[ev.target.name]=ev.target.value;save()};$('#exam-form').onsubmit=ev=>{ev.preventDefault();submitExam()};tick()}
function score(e){return examQuestions(e.version).map(q=>{let value=e.answers[q.id],n=numeric(value??''),ok=q.options?value!==undefined&&String(value)===String(q.answer):Number.isFinite(n)&&Math.abs(n-q.answer)<=q.tolerance;return {...q,value,ok}})}
function submitExam(){let e=S.exam;if(!e||e.submitted)return;e.submitted=true;e.submittedAt=Date.now();e.score=sum(score(e).filter(q=>q.ok).map(q=>q.points));S.history.unshift({time:e.submittedAt,version:e.version,score:e.score});S.history=S.history.slice(0,30);save();if(location.hash==='#exam')exam();else toast('模拟测验时间已到，已自动交卷。')}
function tick(){let e=S.exam;if(!e||e.submitted)return;let remain=Math.max(0,Math.ceil((e.end-Date.now())/1000));if($('#timer'))$('#timer').textContent=`${Math.floor(remain/60)}:${String(remain%60).padStart(2,'0')}`;if(!remain)submitExam()}
function examReport(e){let qs=score(e),weak=[...new Set(qs.filter(q=>!q.ok).map(q=>q.unit))];return `<section class="card section-space"><h2>本次 ${e.version} 卷：自动判分 ${e.score}/86</h2><p>${e.manual==null?'证明题尚待自评，不生成总分。':`证明自评 ${e.manual}/14；合计 ${e.score+e.manual}/100（含自评，未经教师核验）。`}</p><h3>优先修复这些知识点</h3><div class="actions">${weak.length?weak.map(id=>link(id)).join(''):'自动题全部正确。用证明题和隔天复习再检验。'}</div>${qs.map(q=>`<details><summary>${q.ok?'✓':'需复习'} · ${q.prompt}（${q.ok?q.points:0}/${q.points}）</summary><p>你的答案：${q.value===undefined||q.value===''?'未作答':esc(q.options?q.options[Number(q.value)]:q.value)}</p><p>参考：${q.options?q.options[q.answer]:fmt(q.answer)}。${q.explain}</p></details>`).join('')}<h3>证明题参考与自评</h3><p class="math">β̂=(XᵀX)⁻¹Xᵀy<br>=β+(XᵀX)⁻¹Xᵀε<br>E(β̂|X)=β</p><p>满列秩保证 XᵀX 可逆；给定 X 后系数矩阵是常量，E(ε|X)=0 消去误差项。这一证明不需要正态性。</p><details><summary>查看我的证明</summary><p style="white-space:pre-wrap">${esc(e.proof||'未作答')}</p></details><form id="manual"><p class="small">逐项对照自己原来的答案，不能补写后再给原卷加分。</p>${[['写出 OLS 公式且说明可逆',4],['代入 y 并化简为 β 加误差项',4],['正确取条件期望并说明零均值',4],['明确满列秩的作用',2]].map(([t,p],i)=>`<label class="option"><input type="checkbox" name="m${i}" value="${p}" ${e.manualChecks?.includes(i)?'checked':''}> ${t}（${p} 分）</label>`).join('')}<button class="btn secondary">保存证明题自评</button></form></section>`}
function bindManual(){if($('#manual'))$('#manual').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),checks=[0,1,2,3].filter(i=>f.has('m'+i));S.exam.manualChecks=checks;S.exam.manual=sum(checks.map(i=>Number(f.get('m'+i))));let h=S.history.find(h=>h.time===S.exam.submittedAt);if(h)h.manual=S.exam.manual;save();exam()}}
function render(){const [r='today',id,tab]=location.hash.slice(1).split('/');if(r==='learn')learn(id,tab);else if(r==='path')path();else if(r==='rstart')rStart();else if(r==='rtrace')rTrace(id);else if(r==='diagnostic')diagnostic();else if(r==='labs')labs(id);else if(r==='review')review();else if(r==='exam')exam();else if(r==='resources')resources(id);else if(r==='chapter')chapter(id);else if(r==='foundations')foundations();else if(r==='chaptercheck')chapterCheck(id);else if(r==='coursecheck')courseCheck();else today();window.scrollTo(0,0)}
window.addEventListener('hashchange',render);setInterval(tick,1000);render();
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'get_learning_progress',description:'读取本机学习进度，不修改学习记录',inputSchema:{type:'object',properties:{}},annotations:{readOnlyHint:true},execute:async()=>({content:[{type:'text',text:JSON.stringify({lessons:C.lessons.map(l=>({id:l.id,title:l.title,status:status(l)})),due:due().length,next:next().id})}]})});document.modelContext.registerTool({name:'open_lesson',description:'打开指定学习单元，不替学习者答题',inputSchema:{type:'object',properties:{id:{type:'string',enum:C.lessons.map(l=>l.id)}},required:['id']},execute:async({id})=>{if(!lesson(id))throw Error('未知课程');location.hash='learn/'+id;return {content:[{type:'text',text:'已打开 '+lesson(id).title}]}}})}catch(err){console.warn('WebMCP 注册不可用',err)}}
})();
